### ISSUE TITLE
Extension stopped working for fantasy basketball

### ISSUE THREAD

**Issue by DanielLearner** [magnusbakken/espn-fantasy-autopick#13]
I haven't looked into the why, but I suspect it has something to do with the merge from a few days ago.  The "auto (week)" and "auto (day)" buttons have disappeared, the hot keys don't work (there is an error in the console), and the extension name changed to ESPN NHL Fantasy Team Auto Setup

**Comment by magnusbakken** [comment]
Yeah, my bad. I accidentally uploaded the upcoming NHL version of the extension as the existing NBA extension because of a typo in my build script. 🤦 Fixed version is coming very soon.

**Comment by magnusbakken** [comment]
Version 3.0.1 should fix this. Sorry for the inconvenience.
